from getpass import getpass
import os
import time

def menu():
      while True:
           print("")
           os.system('clear')
           print('\033[1;31m                          By Termux Academy')
           print("")
           print("")
           print("")
           print("")
           print("")
           try:
                D = str(input('\033[1;32mUsername \033[1;33m: '))
                print("")
                O = getpass('\033[1;32mPassword \033[1;33m: ')
                print("")
                print("")
                if D=='Academy' and O=='123456789':
                   os.system('clear')
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print('\033[1;32m                                               √  √ ')
                   print('\033[1;32m                                             √  √ ')
                   print('\033[1;32m                                           √  √ ')
                   print('\033[1;32m                              √          √  √ ')
                   print('\033[1;32m                             √  √      √  √ ')
                   print('\033[1;32m                               √  √  √  √ ')
                   print('\033[1;32m                                √   √ √ ')
                   print('\033[1;32m                                 √  √ ')
                   print("")
                   print("")
                   print("\033[1;36m                  👍 Termux now works Welcome To Mr\033[1;32m",D)
                   print("")
                   print("")
                   time.sleep(1)
                   os.system('clear')
                   break
                else:
                      os.system('clear')
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print('\033[1;31m                             √√√√           √√√√')
                      print('\033[1;31m                               √√√√       √√√√')
                      print('\033[1;31m                                 √√√√   √√√√')
                      print('\033[1;31m                                   √√√√ √√')
                      print('\033[1;31m                                   √√√√√')
                      print('\033[1;31m                                 √√√√ √√√√')
                      print('\033[1;31m                               √√√√     √√√√')
                      print('\033[1;31m                             √√√√        √√√√')
                      print("")
                      print("")
                      print('\033[1;35m           😱 The username or password you entered is incorrect 😭')
                      print("")
                      print('\033[1;35m                           Please Try Agian\033[1;31m',D)
                      print("")
                      print("")
                      time.sleep(2)
           except Exception:
                      os.system('clear')
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print('\033[1;31m                             √√√√           √√√√')
                      print('\033[1;31m                               √√√√       √√√√')
                      print('\033[1;31m                                 √√√√   √√√√')
                      print('\033[1;31m                                   √√√√ √√')
                      print('\033[1;31m                                   √√√√√')
                      print('\033[1;31m                                 √√√√ √√√√')
                      print('\033[1;31m                               √√√√     √√√√')
                      print('\033[1;31m                             √√√√        √√√√')
                      print("")
                      print("")
                      print('\033[1;35m           😱 The username or password you entered is incorrect 😭')
                      print("")
                      print('\033[1;35m                           Please Try Agian\033[1;31m',D)
                      print("")
                      print("")
                      time.sleep(2)
           except KeyboardInterrupt:
                      print("")
                      os.system('killall -9 com.termux')
                      os.system('clear')
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print('\033[1;31m                             √√√√           √√√√')
                      print('\033[1;31m                               √√√√       √√√√')
                      print('\033[1;31m                                 √√√√   √√√√')
                      print('\033[1;31m                                   √√√√ √√')
                      print('\033[1;31m                                   √√√√√')
                      print('\033[1;31m                                 √√√√ √√√√')
                      print('\033[1;31m                               √√√√     √√√√')
                      print('\033[1;31m                             √√√√        √√√√')
                      print("")
                      print("")
                      print('\033[1;31m                     😈 There Is No Login On Termux 😋')
                      print("")
                      print('\033[1;31m                             Please Try Agian')
                      print("")
                      print("")
                      time.sleep(2)
menu()
